### ISSUE TITLE
Subsites compatibility

### ISSUE THREAD

**Issue by flashbackzoo** [silverstripe/silverstripe-populate#18]
Hey,

I've run into an issue using populate with [subsites](https://github.com/silverstripe/silverstripe-subsites).

Each subsite is able to have pages with the same URL segment, for example:

mainsite.com/home
mysubsite.com/home

Populate handles URL segment collisions like the CMS does, by prefixing the page id, so you get `home-2` on the subsite URL segment.

Here's a example populate.yml

```yml
Subsite:
  MySubsite:
    Title: 'My Subsite'
    Theme: 'mysubsite'

SubsiteDomain:
  MySubsiteDomain:
    Domain: 'mysubsite.com'
    Protocol: 'automatic'
    Subsite: =>Subsite.MySubsite

Page:
  Home:
    ParentID: 0
    ShowInMenus: false
    Title: 'Home'
    URLSegment: 'home'
  SubsiteHome:
    ParentID: 0
    ShowInMenus: false
    Title: 'Home'
    URLSegment: 'home'
   Subsite: =>Subsite.MySubsite
```

I'm currently working around this by creating an DataExtension on Populate and updating the records manually.

```php
class PopulateExtension extends DataExtension
{
    public function onAfterPopulateRecords()
    {
        // Do stuff
    }
}
```

Is there a way I can populate pages across subsites without having to use the `onAfterPopulateRecords` hook?

Thanks
