### ISSUE TITLE
Locations of populated images are not recognized by the CMS

### ISSUE THREAD

**Issue by anselmdk** [silverstripe/silverstripe-populate#4]
I've started using the "Default assets". I love the concept, though it seems images that are placed in a directory are not properly picked up by the CMS.

It takes for me to sync assets via the cms for this to happen. See screenshots of the issue: 

_Image appears in the root of assets - with no title:_
![screenshot 2014-03-11 22 08 10](https://f.cloud.github.com/assets/1316533/2391040/f4c46104-a961-11e3-9a34-9060ce5226e7.png)

_Even though it should have appeared in this directory (that's also where it's placed):_
![screenshot 2014-03-11 22 08 23](https://f.cloud.github.com/assets/1316533/2391041/f4c59862-a961-11e3-9759-67465add9b36.png)

Initially I thought I could fix this by adding the following to `PopulateFactory.php` before returning the object, as to my knowledge that's what needs to be triggered, it's not working though, so I'm a little lost:

```
//making sure to update file system after adding/editing files and images
if(isset($data['PopulateFileFrom'])) {
    $obj->updateFilesystem();
}
```

This is my yml:

``` yml
Image:
  demo3a:
    Filename: assets/immodb/demos/demo3a.jpg
    PopulateFileFrom: immodb/images/demos/demo3/3761870901_953b1c54c9_b.jpg
    PopulateMergeMatch:
      - Filename
```
##
