### ISSUE TITLE
Images cause error when repeatedly running populate task.

### ISSUE THREAD

**Issue by davejtoews** [silverstripe/silverstripe-populate#45]
Version 2.1.0

Relevant portion of my yml

```yml
SilverStripe\Assets\Image:
  imageOne:
    Created: "1970-01-02 03:04:05"
    Filename: assets/TestContent/imageBlockOne.jpg
    PopulateFileFrom: app/fixtures/assets/546-900x600.jpg
    PopulateMergeMatch:
      - Created

App\Elements\ImageElement:
  imageBlockOne:
    Title: Image Element
    ShowTitle: true
    Created: "1970-01-02 03:04:05"
    ImageID: =>SilverStripe\Assets\Image.imageOne
    ParentID: =>DNADesign\Elemental\Models\ElementalArea.imageArea
    PopulateMergeMatch:
      - Created
```

This runs fine the first time, but on the second pass creating the image results in the following: 

**[Notice] Trying to get property 'ID' of non-object**
_Line 72 in /var/www/html/vendor/dnadesign/silverstripe-populate/code/PopulateFactory.php_

And then attempting to reference the image results in:

**[Emergency] Uncaught InvalidArgumentException: No fixture definitions found for "=>SilverStripe\Assets\Image.imageOne"**
_Line 332 in /var/www/html/vendor/silverstripe/framework/src/Dev/FixtureBlueprint.php_
